### ISSUE TITLE
Date range for events

### ISSUE THREAD

**Issue by kraigrs** [predicthq/sdk-py#14]
How does one use the `start` and `end` parameters here with the `gte` and `lte` suffixes? It's clear with the HTTP request, but I can't figure out how to use it for this SDK.

Thank you!

**Comment by hampsterx** [comment]
good question, it's not that clear is it. You can use double underscore. eg start__gte

Easiest way for now is to check the tests to see some more examples. eg

https://github.com/predicthq/sdk-py/blob/master/tests/endpoints/v1/events_tests.py

**Comment by kraigrs** [comment]
Thank you for the quick response, those tests definitely helped!
