### ISSUE TITLE
Frequent 504 Gateway Time-out Errors

### ISSUE THREAD

**Issue by chrisjkuch** [predicthq/sdk-py#34]
I am having a recurring issue using `iter_all` for a location-based query with thousands of results - I get a `504 Gateway Time-out` response.

I have made some gains by inserting a `sleep` call for a second between fetching new pages of results, but I still see occasional errors.

I might suggest adding a test for a query that will return thousands of events to supplement the existing queries in tests that seem a bit more targeted to smaller results lists.

**Comment by mbonnefoy** [comment]
Hi @chrisjkuch,

Thanks for reporting this issue. We are investigating it at the moment and will get back to you as soon as possible.

Cheers,
Matthieu

**Comment by mbonnefoy** [comment]
Hi @chrisjkuch,

We believe that this issue is now resolved (it was not directly related to the Python client).

Can you please confirm that it's also resolved on your side or provide more information on how to reproduce it?

Thanks,
Matthieu

**Comment by mbonnefoy** [comment]
I am closing this issue, please feel free to reopen if you still experience this problem.
